# Generated by Django 4.2.9 on 2024-01-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhitelistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('addresses', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
            ],
        ),
    ]
