# Generated by Django 4.2.9 on 2024-01-06 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_whitelistrequest_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whitelistrequest',
            name='addresses',
            field=models.TextField(null=True),
        ),
    ]
