# Generated by Django 4.2.9 on 2024-01-08 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_whitelistrequest_addresses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whitelistrequest',
            old_name='user',
            new_name='user_name',
        ),
    ]
